import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { Sidebar } from "@/components/sidebar";
import { updateOrderOperational } from "../actions";
import { QuickStart } from "@/components/quick-start";

export default async function OrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{created?:string;updated?:string;error?:string}>}){
  const {id}=await params;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user) redirect("/login");
  const {data:order}=await supabase.from("optical_orders").select("id,order_code,client_id,sale_id,prescription_id,frame_product_id,lens_product_id,status,lab,lab_reference,lens_type,lens_design,lens_material,lens_index,lens_brand,lens_diameter_mm,lens_center_thickness_mm,lens_edge_thickness_mm,lens_tint_color,treatments,measurements,promised_at,delivered_at,qc_status,pickup_notified_at,delivery_notes,adaptation_followup_at,notes,created_at").eq("id",id).maybeSingle();
  if(!order) redirect("/pedidos?error=Pedido%20no%20encontrado");
  const [{data:client},{data:prescription},{data:sale},{data:frame},{data:lensProduct},{data:audit}]=await Promise.all([
    order.client_id?supabase.from("clients").select("full_name,dni,whatsapp,phone").eq("id",order.client_id).maybeSingle():Promise.resolve({data:null}),
    order.prescription_id?supabase.from("prescriptions").select("exam_at,expires_at,rx_type,cylinder_notation,prescriber_name,prescriber_license,rx_source,od_sphere,od_cylinder,od_axis,od_add,os_sphere,os_cylinder,os_axis,os_add,od_near_sphere,od_near_cylinder,od_near_axis,os_near_sphere,os_near_cylinder,os_near_axis,notes,od_prism_horizontal,od_prism_horizontal_base,od_prism_vertical,od_prism_vertical_base,os_prism_horizontal,os_prism_horizontal_base,os_prism_vertical,os_prism_vertical_base,pd,pd_od,pd_os").eq("id",order.prescription_id).maybeSingle():Promise.resolve({data:null}),
    order.sale_id?supabase.from("sales").select("sale_code,total,payment_status").eq("id",order.sale_id).maybeSingle():Promise.resolve({data:null}),
    order.frame_product_id?supabase.from("products").select("product_code,brand,model,cost,sale_price").eq("id",order.frame_product_id).maybeSingle():Promise.resolve({data:null}),
    order.lens_product_id?supabase.from("products").select("product_code,brand,model,lens_design,lens_material,lens_index,lens_phi_mm,lens_coatings,lens_prism_capable").eq("id",order.lens_product_id).maybeSingle():Promise.resolve({data:null}),
    supabase.from("audit_log").select("id,actor_user_id,action,new_data,created_at").eq("record_id",id).eq("table_name","optical_orders").order("created_at",{ascending:false}).limit(20)
  ]);
  const q=await searchParams;
  const statusSteps=["received","in_preparation","at_lab","ready","delivered"];
  const statusLabels:Record<string,string>={received:"Recibido",in_preparation:"En preparación",at_lab:"En laboratorio",ready:"Listo",delivered:"Entregado",cancelled:"Cancelado"};
  const currentIndex=statusSteps.indexOf(order.status);
  const primaryRxLabel = prescription?.rx_type === "Cerca" ? "Cerca / principal" : ["Lejos","Lejos y cerca","Bifocal","Progresivo","Ocupacional"].includes(prescription?.rx_type || "") ? "Lejos / principal" : "Principal";
  return <div className="shell"><Sidebar/><main className="main"><header className="topbar"><strong>Pedido óptico</strong><span className="muted">Ficha de producción</span></header><div className="content">
    <div className="spread"><div><h1 className="page-title">{order.order_code}</h1><p className="subtitle">{client?.full_name||"Cliente"} · creado {new Date(order.created_at).toLocaleDateString("es-PE")}</p></div><a className="btn btn-secondary" href="/pedidos">Volver</a></div>
    <QuickStart title="Inicio rápido del pedido" hint="Revisa en este orden: progreso → configuración → medidas/receta → QC → aviso → entrega." items={[
  {label:"Progreso",href:"#progreso",description:"Estado actual del trabajo",tone:"blue"},
  {label:"Configuración óptica",href:"#configuracion",description:"Lunas, tratamientos y laboratorio",tone:"purple"},
  {label:"QC y entrega",href:"#actualizar-flujo",description:"Valida antes de entregar",tone:"orange"},
  {label:"Postventa",href:"/seguimientos",description:"Agenda adaptación",tone:"green"}
]}/>
{q.error&&<p className="notice" style={{marginTop:18}}>{q.error}</p>}
{q.created&&<p className="notice" style={{marginTop:18}}>Pedido creado.</p>}
{q.updated&&<p className="notice" style={{marginTop:18}}>Pedido actualizado.</p>}
    <section id="progreso" className="card section"><div className="spread"><div><h2 style={{marginBottom:4}}>Progreso</h2><p className="muted">Recibido → preparación → laboratorio → listo → entrega.</p></div><span className={`status-badge ${order.status==="delivered"?"status-success":order.status==="ready"?"status-info":order.status==="cancelled"?"status-danger":"status-warning"}`}>{statusLabels[order.status]||order.status}</span></div>{order.status==="cancelled"?<div className="notice" style={{marginTop:12}}>Pedido cancelado.</div>:<div className="order-progress">{statusSteps.map((step,i)=><div className={"order-step "+(i<currentIndex?"done ":"")+(i===currentIndex?"current":"")} key={step}><span className="order-dot">{i<currentIndex?"✓":i+1}</span><span>{statusLabels[step]}</span></div>)}</div>}</section>
    <section className="grid grid-4 section"><div className="card"><div className="metric-label">Estado</div><div className="metric-value" style={{fontSize:20}}>{statusLabels[order.status]||order.status}</div></div><div className="card"><div className="metric-label">QC</div><div className="metric-value" style={{fontSize:20}}><span className={`status-badge ${order.qc_status==="approved"?"status-success":order.qc_status==="rework"?"status-danger":"status-warning"}`}>{order.qc_status}</span></div></div><div className="card"><div className="metric-label">Prometido</div><div className="metric-value" style={{fontSize:18}}>{order.promised_at?new Date(order.promised_at).toLocaleDateString("es-PE"):"Sin fecha"}</div></div><div className="card"><div className="metric-label">Aviso</div><div className="metric-value" style={{fontSize:18}}>{order.pickup_notified_at?"Enviado":"Pendiente"}</div></div></section>
    <section className="grid grid-3 section"><div className="card"><h2>Cliente</h2><p>{client?.full_name||"·"}</p><p className="muted">{client?.dni||""} {client?.whatsapp||client?.phone||""}</p></div><div className="card"><h2>Venta</h2><p>{sale?.sale_code||"Sin vínculo"}</p><p className="muted">{sale?"S/ "+Number(sale.total).toFixed(2)+" · "+sale.payment_status:"·"}</p></div><div className="card"><h2>Montura</h2><p>{frame?[frame.brand,frame.model].filter(Boolean).join(" "):"Sin vínculo"}</p><p className="muted">{frame?.product_code||""}</p></div></section>
    <section id="configuracion" className="card section"><h2>Configuración de lunas</h2><p className="muted">Datos de selección y fabricación que deben coincidir con la receta y la confirmación del laboratorio.</p><div className="grid grid-3"><div><strong>Diseño</strong><p>{order.lens_design||"·"}</p></div><div><strong>Tipo / tecnología</strong><p>{order.lens_type||"·"}</p></div><div><strong>Material</strong><p>{order.lens_material||"·"}</p></div><div><strong>Índice</strong><p>{order.lens_index||"·"}</p></div><div><strong>Diámetro mínimo / PHI</strong><p>{order.lens_diameter_mm?Number(order.lens_diameter_mm)+" mm":"·"}</p></div><div><strong>Espesor central objetivo</strong><p>{order.lens_center_thickness_mm?Number(order.lens_center_thickness_mm)+" mm":"·"}</p></div><div><strong>Espesor de borde objetivo</strong><p>{order.lens_edge_thickness_mm?Number(order.lens_edge_thickness_mm)+" mm":"·"}</p></div><div><strong>Marca</strong><p>{order.lens_brand||"·"}</p></div><div><strong>Tinte / color</strong><p>{order.lens_tint_color||"·"}</p></div><div><strong>Tratamientos</strong><p>{order.treatments||"·"}</p></div><div><strong>Laboratorio</strong><p>{order.lab||"·"}</p></div><div><strong>Referencia de laboratorio</strong><p>{order.lab_reference||"·"}</p></div><div><strong>Producto del catálogo</strong><p>{lensProduct?[lensProduct.brand,lensProduct.model].filter(Boolean).join(" ")||lensProduct.product_code:order.lens_product_id?"Producto no disponible":"Configuración manual"}</p>{lensProduct&&<p className="muted">{lensProduct.product_code} · <Link href="/buscador-lunas" className="link-strong">Buscar otra luna</Link></p>}</div><div><strong>Recubrimientos declarados</strong><p>{lensProduct?(lensProduct.lens_coatings??[]).join(" · ")||"No registrados":order.treatments||"·"}</p></div></div></section>
    <section className="card section"><h2>Centrado y medidas de montaje</h2><p className="muted">Todas las medidas son opcionales si no fueron tomadas. No rellenes valores por estimación: confirma unidades y ojo antes de mandar a laboratorio.</p><div className="table-wrap"><table style={{minWidth:900}}><thead><tr><th>Medida</th><th>OD</th><th>OI</th><th>Binocular / general</th></tr></thead><tbody>
      <tr><th>DP de lejos</th><td>{order.measurements?.pd_od||"·"} mm</td><td>{order.measurements?.pd_os||"·"} mm</td><td>{order.measurements?.pd_binocular||"·"} mm</td></tr>
      <tr><th>DP de cerca</th><td>{order.measurements?.pd_near_od||"·"} mm</td><td>{order.measurements?.pd_near_os||"·"} mm</td><td>{order.measurements?.pd_near_binocular||"·"} mm</td></tr>
      <tr><th>Altura de montaje</th><td>{order.measurements?.height_od||"·"} mm</td><td>{order.measurements?.height_os||"·"} mm</td><td>·</td></tr>
      <tr><th>Montura</th><td>A {order.measurements?.frame_a||"·"} mm</td><td>B {order.measurements?.frame_b||"·"} mm</td><td>ED {order.measurements?.frame_ed||"·"} · DBL {order.measurements?.frame_dbl||"·"} · Patilla {order.measurements?.frame_temple||"·"} · Frontal {order.measurements?.frame_front_width||"·"} mm</td></tr>
      <tr><th>Ajuste</th><td>{order.measurements?.vertex||"·"} mm de vértice</td><td>{order.measurements?.pantoscopic||"·"}° pantoscópica</td><td>{order.measurements?.wrap||"·"}° envolvimiento</td></tr>
      <tr><th>Uso especial</th><td>Trabajo {order.measurements?.working_distance_cm||"·"} cm</td><td>Montaje {order.measurements?.mounting_type||"·"}</td><td>{order.measurements?.frame_reference||"·"}</td></tr>
    </tbody></table></div>
    {order.measurements?.measurement_notes&&<div className="notice" style={{marginTop:12}}><strong>Notas de medidas:</strong> {order.measurements.measurement_notes}</div>}</section>
    {prescription&&<section className="card section"><h2>Receta vinculada</h2><p className="muted">{new Date(prescription.exam_at).toLocaleDateString("es-PE")}{prescription.expires_at?" · vence "+new Date(prescription.expires_at).toLocaleDateString("es-PE"):""} · {prescription.rx_type||"Uso no indicado"} · cilindro {prescription.cylinder_notation==="positive"?"positivo":"negativo"}</p><p>Prescriptor: {prescription.prescriber_name||"No indicado"}{prescription.prescriber_license?" · registro "+prescription.prescriber_license:""}{prescription.rx_source?" · origen: "+prescription.rx_source:""}</p>
      <div className="table-wrap"><table style={{minWidth:1050}}><thead><tr><th>Visión</th><th>Ojo</th><th>Esfera</th><th>Cilindro</th><th>Eje</th><th>ADD</th><th>Prisma horizontal</th><th>Base H</th><th>Prisma vertical</th><th>Base V</th></tr></thead><tbody>
        <tr><th>{primaryRxLabel}</th><th>OD</th><td>{prescription.od_sphere??"·"}</td><td>{prescription.od_cylinder??"·"}</td><td>{prescription.od_axis??"·"}</td><td>{prescription.od_add??"·"}</td><td>{prescription.od_prism_horizontal??"·"}</td><td>{prescription.od_prism_horizontal_base||"·"}</td><td>{prescription.od_prism_vertical??"·"}</td><td>{prescription.od_prism_vertical_base||"·"}</td></tr>
        <tr><th>{primaryRxLabel}</th><th>OI</th><td>{prescription.os_sphere??"·"}</td><td>{prescription.os_cylinder??"·"}</td><td>{prescription.os_axis??"·"}</td><td>{prescription.os_add??"·"}</td><td>{prescription.os_prism_horizontal??"·"}</td><td>{prescription.os_prism_horizontal_base||"·"}</td><td>{prescription.os_prism_vertical??"·"}</td><td>{prescription.os_prism_vertical_base||"·"}</td></tr>
        <tr><th>Cerca</th><th>OD</th><td>{prescription.od_near_sphere??"·"}</td><td>{prescription.od_near_cylinder??"·"}</td><td>{prescription.od_near_axis??"·"}</td><td>·</td><td>·</td><td>·</td><td>·</td><td>·</td></tr>
        <tr><th>Cerca</th><th>OI</th><td>{prescription.os_near_sphere??"·"}</td><td>{prescription.os_near_cylinder??"·"}</td><td>{prescription.os_near_axis??"·"}</td><td>·</td><td>·</td><td>·</td><td>·</td><td>·</td></tr>
      </tbody></table></div>
      <p className="muted">DP binocular: {prescription.pd??"·"} mm · DP OD: {prescription.pd_od??"·"} mm · DP OI: {prescription.pd_os??"·"} mm</p>{prescription.notes&&<p><strong>Observaciones:</strong> {prescription.notes}</p>}</section>}
    <section id="actualizar-flujo" className="card section"><h2>Actualizar flujo</h2><form action={updateOrderOperational} className="form"><input type="hidden" name="order_id" value={order.id}/><div className="form-grid"><div className="field"><label>Estado</label><select name="status" defaultValue={order.status}><option value="received">Recibido</option><option value="in_preparation">En preparación</option><option value="at_lab">En laboratorio</option><option value="ready">Listo</option><option value="delivered">Entregado</option><option value="cancelled">Cancelado</option></select></div><div className="field"><label>Control de calidad</label><select name="qc_status" defaultValue={order.qc_status}><option value="pending">Pendiente</option><option value="approved">Aprobado</option><option value="rework">Rehacer</option></select></div><div className="field"><label>Referencia laboratorio</label><input name="lab_reference" defaultValue={order.lab_reference||""}/></div><div className="field"><label>Adaptación / seguimiento</label><input name="adaptation_followup_at" type="datetime-local" defaultValue={order.adaptation_followup_at?new Date(order.adaptation_followup_at).toISOString().slice(0,16):""}/></div><div className="field"><label>Notas de entrega</label><input name="delivery_notes" defaultValue={order.delivery_notes||""}/></div></div><label className="checkline"><input type="checkbox" name="pickup_notified" defaultChecked={!!order.pickup_notified_at}/> Cliente avisado para recojo</label><button className="btn btn-primary">Guardar estado</button></form></section>
  </div></main></div>;
}